---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infrastructure:
    - Internet:
        icon: avm-fritzbox
        href: http://router
        ping: router
        widget:
          type: fritzbox
          url: http://router
    - DNS:
        icon: pi-hole
        href: http://dnsdhcp/admin
        ping: dnsdhcp
        widget:
          type: pihole
          url: http://dnsdhcp
          version: 6
          key: {{HOMEPAGE_VAR_PIHOLE_KEY}}
    - Web Server:
        icon: caddy
        ping: caddy
        server: localhost-docker
        container: caddy
        widget:
          type: caddy
          url: http://caddy:2019
    - Monitoring:
        icon: prometheus
        href: http://prometheus.{{HOMEPAGE_VAR_DOMAIN}}
        description: prometheus.{{HOMEPAGE_VAR_DOMAIN}}
        ping: prometheus
        server: localhost-docker
        container: prometheus
        widget:
          type: prometheus
          url: http://prometheus:9090
- Services:
    - Document Archive:
        icon: paperless-ngx
        href: http://paperless.{{HOMEPAGE_VAR_DOMAIN}}
        description: paperless.{{HOMEPAGE_VAR_DOMAIN}}
        ping: paperless-webserver
        server: localhost-docker
        container: paperless-webserver
        widget:
          type: paperlessngx
          url: http://paperless-webserver:8000
          username: {{HOMEPAGE_VAR_PAPERLESS_USER}}
          password: {{HOMEPAGE_VAR_PAPERLESS_PASSWORD}}
    - Photos:
        icon: immich
        href: http://immich.{{HOMEPAGE_VAR_DOMAIN}}
        description: immich.{{HOMEPAGE_VAR_DOMAIN}}
        ping: immich_server
        server: localhost-docker
        container: immich_server
        widget:
          type: immich
          url: http://immich-server:2283
          key: {{HOMEPAGE_VAR_IMMICH_KEY}}
          version: 2
    - Grafana:
        icon: grafana
        href: http://grafana.{{HOMEPAGE_VAR_DOMAIN}}
        description: grafana.{{HOMEPAGE_VAR_DOMAIN}}
        ping: grafana
        server: localhost-docker
        container: grafana
        widget:
          type: grafana
          url: http://grafana:3000
          username: {{HOMEPAGE_VAR_GRAFANA_USER}}
          password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
    - InfluxDB:
        href: http://influxdb2.{{HOMEPAGE_VAR_DOMAIN}}
        description: influxdb2.{{HOMEPAGE_VAR_DOMAIN}}
        ping: influxdb2
        server: localhost-docker
        container: influxdb2
