services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 4000:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse_proxy_net
    env_file:
      - ../.env.private.docker
networks:
  reverse_proxy_net:
    external: true
