{
 "title": "Nodes",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"node\"},instance)"
    }
   },
   { "name": "node_exporter_port", "query": "9100" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inventory",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "node_os_info", "legendFormat": "__auto" },
    {
     "expr": "node_memory_MemTotal_bytes or node_memory_size_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "count without(cpu) (node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (node_filesystem_size_bytes{fstype!=\"zfs\"} or zfs_zpool_size_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (avg by (instance)  (rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_time_seconds - node_boot_time_seconds)",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (node_memory_MemAvailable_bytes or (node_memory_free_bytes + node_zfs_arcstats_size_bytes)) / (node_memory_MemTotal_bytes or node_memory_size_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "1- node_filesystem_free_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (instance) ((1 - (node_filesystem_free_bytes{fstype=\"zfs\"} or node_filesystem_free_bytes{mountpoint=\"/home\"}) / (node_filesystem_size_bytes{fstype=\"zfs\"} or node_filesystem_size_bytes{mountpoint=\"/home\"})))",
     "legendFormat": "__auto"
    },
    { "expr": "node_reboot_required", "legendFormat": "__auto" },
    {
     "expr": "apt_upgrades_pending or freebsd_update_pending_install",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Overall",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(node_cpu_seconds_total{instance=\"${instance}:${node_exporter_port}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "stat",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"${instance}:${node_exporter_port}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_cpu_temperature_celsius{instance=\"${instance}:${node_exporter_port}\"} or node_hwmon_temp_celsius{chip=\"pci0000:00_0000:00:18_3\",sensor=\"temp1\",instance=\"${instance}:${node_exporter_port}\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "core/mode",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (mode,cpu) (rate(node_cpu_seconds_total{instance=\"${instance}:${node_exporter_port}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM (FreeBSD)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node_memory_active_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_memory_buffer_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "node_memory_cache_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Cache"
      },
      {
       "expr": "node_memory_free_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_inactive_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Inactive"
      },
      {
       "expr": "node_memory_laundry_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Laundry"
      },
      {
       "expr": "node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Size"
      },
      {
       "expr": "node_memory_swap_size_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Swap Size"
      },
      {
       "expr": "node_memory_swap_used_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Swap Used"
      },
      {
       "expr": "node_memory_user_wired_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Wired User"
      },
      {
       "expr": "node_memory_wired_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Wired System"
      }
     ]
    }
   ]
  },
  {
   "title": "RAM (Linux)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node_memory_Buffers_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_MemTotal_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_MemTotal_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Cached"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_MemTotal_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_MemTotal_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Slab"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_MemTotal_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_MemTotal_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystems",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "node_filesystem_size_bytes{instance=\"${instance}:${node_exporter_port}\"} - node_filesystem_free_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "node_filesystem_avail_bytes{instance=\"${instance}:${node_exporter_port}\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "1 - (node_filesystem_free_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_filesystem_size_bytes{instance=\"${instance}:${node_exporter_port}\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "ZFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "ARC Allocation",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_free_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_zfs_arcstats_size_bytes{instance=\"${instance}:${node_exporter_port}\"} / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"} - (node_memory_free_bytes{instance=\"${instance}:${node_exporter_port}\"} + node_zfs_arcstats_size_bytes{instance=\"${instance}:${node_exporter_port}\"})) / node_memory_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ARC Hits",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arcstats_hits_total{instance=\"${instance}:${node_exporter_port}\"} / (node_zfs_arcstats_hits_total{instance=\"${instance}:${node_exporter_port}\"} + node_zfs_arcstats_misses_total{instance=\"${instance}:${node_exporter_port}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 47 },
   "targets": [
    {
     "expr": "zfs_zpool{instance=\"${instance}:${node_exporter_port}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_zpool_size_bytes{instance=\"${instance}:${node_exporter_port}\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zfs_zpool_free_bytes{instance=\"${instance}:${node_exporter_port}\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}