services:
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    restart: always
    env_file:
      - ../.env.private.docker
    healthcheck:
      test: curl -s http://localhost:3000/share/healthcheck -o /dev/null || exit 1
      start_period: 10s
      timeout: 5s
    networks:
      - reverse_proxy_net

networks:
  reverse_proxy_net:
    external: true
