{
 "title": "Heating",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Heizöl vs Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"heater_boiler_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"outdoortemp\")\n  |> aggregateWindow(every: 24h, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"heatoil\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percentage\")\n  |> aggregateWindow(every: 24h, fn: median, createEmpty: false)\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "Heizung Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"heater_boiler_data\" or r[\"_measurement\"] == \"heater_thermostat_data_hc1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"curflowtemp\" or r[\"_field\"] == \"selflowtemp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Heizung Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"heater_boiler_data_dhw\" or r[\"_measurement\"] == \"heater_boiler_data\" or r[\"_measurement\"] == \"heater_thermostat_data_hc1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"curburnpow\" or r[\"_field\"] == \"outdoortemp\" or r[\"_field\"] == \"exhausttemp\" or r[\"_field\"] == \"curtemp\" or r[\"_field\"] == \"seltemp\" or r[\"_field\"] == \"selflowtemp\" or r[\"_field\"] == \"curflowtemp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)\n  |> yield(name: \"median\")"
    }
   ]
  },
  {
   "title": "Feuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ccu3_HUMIDITY\")\n  |> filter(fn: (r) => r[\"location\"] != \"\")\n  |> group(columns: [\"location\"])\n  |> filter(fn: (r) => r[\"channel\"] == \"1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Thermostat Ventilöffnung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ccu3_LEVEL\")\n  |> filter(fn: (r) => r[\"location\"] != \"\")\n  |> group(columns: [\"location\"])\n  |> filter(fn: (r) => r[\"channel\"] == \"1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Zimmertemperatur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ccu3_ACTUAL_TEMPERATURE\")\n  |> filter(fn: (r) => r[\"location\"] != \"\")\n  |> group(columns: [\"location\"])\n  |> filter(fn: (r) => r[\"channel\"] == \"1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}