{
 "title": "Overview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Außentemperatur",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"heater_boiler_data\" and\n    r._field == \"outdoortemp\"\n  )\n |> aggregateWindow(every: 1m, fn: last)\n"
    }
   ]
  },
  {
   "title": "Tageslicht",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"ccu3_ILLUMINATION\" and\n    r._field == \"ILLUMINATION\"\n  )"
    }
   ]
  },
  {
   "title": "Heizöl",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"heatoil\" and\n    r._field == \"percentage\"\n  )\n  |> last()"
    }
   ]
  },
  {
   "title": "Elektrizität",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\n\nFirst = from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ccu3_ENERGY_COUNTER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ENERGY_COUNTER\")\n  |> filter(fn: (r) => r[\"channel\"] == \"2\")\n  |> first()\n\nLast = from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ccu3_ENERGY_COUNTER\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ENERGY_COUNTER\")\n  |> filter(fn: (r) => r[\"channel\"] == \"2\")\n  |> last()\n\nunion(tables: [First, Last])\n  |> difference()\n  |> map(fn: (r) => ({r with _value: math.abs(x: r._value)}))\n"
    }
   ]
  },
  {
   "title": "Warmwasser",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"heater_boiler_data_dhw\")\n  |> filter(fn: (r) => r[\"_field\"] == \"curtemp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Zimmertemperatur",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ccu3_ACTUAL_TEMPERATURE\")\n  |> filter(fn: (r) => r[\"location\"] != \"\")\n  |> group(columns: [\"location\"])\n  |> filter(fn: (r) => r[\"channel\"] == \"1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Feuchtigkeit",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ww29\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ccu3_HUMIDITY\")\n  |> filter(fn: (r) => r[\"location\"] != \"\")\n  |> group(columns: [\"location\"])\n  |> filter(fn: (r) => r[\"channel\"] == \"1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}