apiVersion: 1

prune: true

datasources:
  - name: influxdb2
    type: influxdb
    access: proxy
    url: http://influxdb2:8086
    jsonData:
      version: Flux
      organization: $INFLUXDB2_ORG
      defaultBucket: ww29
      tlsSkipVerify: false
    secureJsonData:
      token: $INFLUXDB2_TOKEN
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 3.3.0
      cacheLevel: 'Low'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      timeInterval: 1m
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      timeout: 60
      maxLines: 700
